# Generated by Django 5.2.16 on 2026-07-21 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(blank=True, max_length=50, null=True)),
                ('icd10_name', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('onset_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_type', models.CharField(blank=True, max_length=100, null=True)),
                ('encounter_date', models.DateTimeField()),
                ('status', models.CharField(default='In-Progress', max_length=50)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('subjective_note', models.TextField(blank=True, null=True)),
                ('objective_note', models.TextField(blank=True, null=True)),
                ('assessment_note', models.TextField(blank=True, null=True)),
                ('plan_note', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
    ]
