# Generated by Django 5.2.16 on 2026-07-21 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequestTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analyte_name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('turnaround_hours', models.IntegerField(default=24)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('urgency', models.CharField(default='Routine', max_length=50)),
                ('clinical_indication', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Requested', max_length=50)),
                ('specimen_id', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('has_critical', models.BooleanField(default=False)),
                ('report_url', models.URLField(blank=True, max_length=500, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='clinical.encounter')),
            ],
        ),
    ]
