# Generated by Django 5.2.16 on 2026-07-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequesttest',
            name='lab_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_tests', to='laboratory.labrequest'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labrequest'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_request_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labrequesttest'),
        ),
        migrations.AddField(
            model_name='labrequesttest',
            name='test_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_tests', to='laboratory.labtestcatalog'),
        ),
    ]
