# Generated by Django 5.2.16 on 2026-07-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0003_initial'),
        ('patients', '0002_initial'),
        ('pharmacy', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='users.department'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.inventoryitem'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescription_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='pharmacy.inventorybatch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pharmacy.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_stock_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
