# Generated by Django 5.2.16 on 2026-07-21 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('admission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_date', models.DateTimeField()),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('provisional_diagnosis', models.TextField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True, null=True)),
                ('discharge_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Admitted', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bed_type', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
