# Generated by Django 5.2.16 on 2026-07-21 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('appointment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.IntegerField()),
                ('priority', models.CharField(default='Normal', max_length=50)),
                ('status', models.CharField(default='Waiting', max_length=50)),
                ('queue_date', models.DateField()),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
