# Generated by Django 5.2.16 on 2026-07-21 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('findings', models.TextField(blank=True, null=True)),
                ('impression', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('critical_finding', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('digitally_signed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(max_length=100)),
                ('body_part', models.CharField(blank=True, max_length=100, null=True)),
                ('urgency', models.CharField(default='Routine', max_length=50)),
                ('clinical_indication', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Requested', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('report_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
