# Generated by Django 5.2.16 on 2026-07-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0003_initial'),
        ('patients', '0002_initial'),
        ('radiology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_requests', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='radiology_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='radiology.radiologyrequest'),
        ),
    ]
