# Generated by Django 5.2.16 on 2026-07-21 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(default='Normal', max_length=50)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('sms_status', models.CharField(blank=True, max_length=50, null=True)),
                ('email_status', models.CharField(blank=True, max_length=50, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
